[package]
name = "step_planning_solver"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre.workspace = true
geometry.workspace = true
linear_algebra.workspace = true
nalgebra.workspace = true
nlopt.workspace = true
num-dual.workspace = true
step_planning.workspace = true
types.workspace = true
