[package]
name = "partial"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
partial_derive.workspace = true

[dev-dependencies]
serde.workspace = true
